/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gabriellecozart
 */
public class OreoAlarmClockJFrame extends javax.swing.JFrame {

    /**
     * Creates new form OreoAlarmClockJFrame
     */
    public OreoAlarmClockJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FMAMButtonGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ClockPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        HourButton = new javax.swing.JButton();
        MinuteButton = new javax.swing.JButton();
        SnoozeButton = new javax.swing.JButton();
        TimeToggleButton = new javax.swing.JToggleButton();
        Alarm1ToggleButton = new javax.swing.JToggleButton();
        Alarm2ToggleButton = new javax.swing.JToggleButton();
        TimeLabel = new javax.swing.JLabel();
        RadioPanel = new javax.swing.JPanel();
        FrequencyLabel = new javax.swing.JLabel();
        FMButton = new javax.swing.JRadioButton();
        AMButton = new javax.swing.JRadioButton();
        IncrementVolumeButton = new javax.swing.JButton();
        VolumeLabel = new javax.swing.JLabel();
        DecrementVolumeButton = new javax.swing.JButton();
        IncrementFrequencyButton = new javax.swing.JButton();
        DecrementFrequencyButton = new javax.swing.JButton();
        VolumeDisplay = new javax.swing.JLabel();

        FMAMButtonGroup.add(AMButton);
        FMAMButtonGroup.add(FMButton);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBorder(new javax.swing.border.MatteBorder(null));

        HourButton.setText("Hour");
        HourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HourButtonActionPerformed(evt);
            }
        });

        MinuteButton.setText("Minute");

        SnoozeButton.setText("Snooze");
        SnoozeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnoozeButtonActionPerformed(evt);
            }
        });

        TimeToggleButton.setText("Set Time");

        Alarm1ToggleButton.setText("Set Alarm 1");

        Alarm2ToggleButton.setText("Set Alarm 2");

        TimeLabel.setFont(new java.awt.Font("Lucida Sans", 0, 48)); // NOI18N
        TimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TimeLabel.setText("12:00 AM");
        TimeLabel.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(TimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Alarm1ToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Alarm2ToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(TimeToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(MinuteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SnoozeButton)
                .addGap(75, 75, 75))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HourButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TimeToggleButton))
                        .addGap(41, 41, 41))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SnoozeButton)
                            .addComponent(MinuteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alarm2ToggleButton)
                    .addComponent(Alarm1ToggleButton))
                .addGap(33, 33, 33)
                .addComponent(TimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout ClockPanelLayout = new javax.swing.GroupLayout(ClockPanel);
        ClockPanel.setLayout(ClockPanelLayout);
        ClockPanelLayout.setHorizontalGroup(
            ClockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClockPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ClockPanelLayout.setVerticalGroup(
            ClockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Clock", ClockPanel);

        FrequencyLabel.setFont(new java.awt.Font("Lucida Sans", 0, 48)); // NOI18N
        FrequencyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FrequencyLabel.setText("87.5 FM");
        FrequencyLabel.setToolTipText("");

        FMButton.setText("FM");

        AMButton.setText("AM");

        IncrementVolumeButton.setText("Increment Volume");

        VolumeLabel.setText("Volume: ");

        DecrementVolumeButton.setText("Decrement Volume");

        IncrementFrequencyButton.setText("Increment Frequency");

        DecrementFrequencyButton.setText("Decrement Frequency");

        VolumeDisplay.setText("5");

        javax.swing.GroupLayout RadioPanelLayout = new javax.swing.GroupLayout(RadioPanel);
        RadioPanel.setLayout(RadioPanelLayout);
        RadioPanelLayout.setHorizontalGroup(
            RadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RadioPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FMButton)
                .addGap(86, 86, 86)
                .addComponent(AMButton)
                .addGap(178, 178, 178))
            .addGroup(RadioPanelLayout.createSequentialGroup()
                .addGroup(RadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(RadioPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IncrementFrequencyButton)
                        .addGap(18, 18, 18)
                        .addComponent(DecrementFrequencyButton))
                    .addGroup(RadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(RadioPanelLayout.createSequentialGroup()
                            .addGap(126, 126, 126)
                            .addComponent(FrequencyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(RadioPanelLayout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(IncrementVolumeButton)
                            .addGap(18, 18, 18)
                            .addComponent(DecrementVolumeButton)
                            .addGap(34, 34, 34)
                            .addComponent(VolumeLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(VolumeDisplay))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        RadioPanelLayout.setVerticalGroup(
            RadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RadioPanelLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(RadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IncrementFrequencyButton)
                    .addComponent(DecrementFrequencyButton))
                .addGap(43, 43, 43)
                .addGroup(RadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DecrementVolumeButton)
                    .addComponent(IncrementVolumeButton)
                    .addComponent(VolumeLabel)
                    .addComponent(VolumeDisplay))
                .addGap(48, 48, 48)
                .addComponent(FrequencyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AMButton)
                    .addComponent(FMButton))
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Radio", RadioPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Clock");

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SnoozeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnoozeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SnoozeButtonActionPerformed

    private void HourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HourButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HourButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OreoAlarmClockJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OreoAlarmClockJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OreoAlarmClockJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OreoAlarmClockJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OreoAlarmClockJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AMButton;
    private javax.swing.JToggleButton Alarm1ToggleButton;
    private javax.swing.JToggleButton Alarm2ToggleButton;
    private javax.swing.JPanel ClockPanel;
    private javax.swing.JButton DecrementFrequencyButton;
    private javax.swing.JButton DecrementVolumeButton;
    private javax.swing.ButtonGroup FMAMButtonGroup;
    private javax.swing.JRadioButton FMButton;
    private javax.swing.JLabel FrequencyLabel;
    private javax.swing.JButton HourButton;
    private javax.swing.JButton IncrementFrequencyButton;
    private javax.swing.JButton IncrementVolumeButton;
    private javax.swing.JButton MinuteButton;
    private javax.swing.JPanel RadioPanel;
    private javax.swing.JButton SnoozeButton;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JToggleButton TimeToggleButton;
    private javax.swing.JLabel VolumeDisplay;
    private javax.swing.JLabel VolumeLabel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
