
import com.csci360.alarmclock.Controller;
import com.csci360.alarmclock.Time;
import java.awt.Color;
import java.util.Timer;
import java.util.TimerTask;
import java.util.concurrent.TimeUnit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gabriellecozart
 */
public class OreoAlarmClockJFrame extends javax.swing.JFrame {

    /**
     * Creates new form OreoAlarmClockJFrame
     */
    public OreoAlarmClockJFrame() {
        initComponents();
        Timer timer = new Timer();
        this.controller = Controller.start();
        
        TimerTask task = new TimerTask()
        {
            public void run()
            {
                updateTimeLabel();
            }
        };
        timer.schedule(task, 500, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FMAMButtonGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ClockPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        HourButton = new javax.swing.JButton();
        MinuteButton = new javax.swing.JButton();
        SnoozeButton = new javax.swing.JButton();
        TimeToggleButton = new javax.swing.JToggleButton();
        Alarm1ToggleButton = new javax.swing.JToggleButton();
        Alarm2ToggleButton = new javax.swing.JToggleButton();
        TimeLabel = new javax.swing.JLabel();
        Alarm1OnOffSwitch = new javax.swing.JToggleButton();
        Alarm2OnOffSwitch = new javax.swing.JToggleButton();
        RadioPanel = new javax.swing.JPanel();
        FrequencyLabel = new javax.swing.JLabel();
        FMButton = new javax.swing.JRadioButton();
        AMButton = new javax.swing.JRadioButton();
        IncrementVolumeButton = new javax.swing.JButton();
        VolumeLabel = new javax.swing.JLabel();
        DecrementVolumeButton = new javax.swing.JButton();
        IncrementFrequencyButton = new javax.swing.JButton();
        DecrementFrequencyButton = new javax.swing.JButton();
        VolumeDisplay = new javax.swing.JLabel();

        FMAMButtonGroup.add(AMButton);
        FMAMButtonGroup.add(FMButton);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBorder(new javax.swing.border.MatteBorder(null));

        HourButton.setText("Hour");
        HourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HourButtonActionPerformed(evt);
            }
        });

        MinuteButton.setText("Minute");
        MinuteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinuteButtonActionPerformed(evt);
            }
        });

        SnoozeButton.setText("Snooze");
        SnoozeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnoozeButtonActionPerformed(evt);
            }
        });

        TimeToggleButton.setText("Set Time");
        TimeToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeToggleButtonActionPerformed(evt);
            }
        });

        Alarm1ToggleButton.setText("Set Alarm 1");
        Alarm1ToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alarm1ToggleButtonActionPerformed(evt);
            }
        });

        Alarm2ToggleButton.setText("Set Alarm 2");
        Alarm2ToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alarm2ToggleButtonActionPerformed(evt);
            }
        });

        TimeLabel.setFont(new java.awt.Font("Lucida Sans", 0, 48)); // NOI18N
        TimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TimeLabel.setText("12:00 AM");
        TimeLabel.setToolTipText("");

        Alarm1OnOffSwitch.setText("Alarm 1 Off");
        Alarm1OnOffSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alarm1OnOffSwitchActionPerformed(evt);
            }
        });

        Alarm2OnOffSwitch.setText("Alarm 2 Off");
        Alarm2OnOffSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alarm2OnOffSwitchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Alarm1OnOffSwitch)
                        .addGap(138, 138, 138)
                        .addComponent(Alarm2OnOffSwitch))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(TimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(Alarm1ToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Alarm2ToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(TimeToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(HourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(MinuteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(SnoozeButton))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HourButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TimeToggleButton)
                    .addComponent(MinuteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SnoozeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alarm1ToggleButton)
                    .addComponent(Alarm2ToggleButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alarm1OnOffSwitch)
                    .addComponent(Alarm2OnOffSwitch))
                .addGap(33, 33, 33)
                .addComponent(TimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout ClockPanelLayout = new javax.swing.GroupLayout(ClockPanel);
        ClockPanel.setLayout(ClockPanelLayout);
        ClockPanelLayout.setHorizontalGroup(
            ClockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClockPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ClockPanelLayout.setVerticalGroup(
            ClockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Clock", ClockPanel);

        FrequencyLabel.setFont(new java.awt.Font("Lucida Sans", 0, 48)); // NOI18N
        FrequencyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FrequencyLabel.setText("87.5 FM");
        FrequencyLabel.setToolTipText("");

        FMButton.setText("FM");

        AMButton.setText("AM");

        IncrementVolumeButton.setText("Increment Volume");

        VolumeLabel.setText("Volume: ");

        DecrementVolumeButton.setText("Decrement Volume");

        IncrementFrequencyButton.setText("Increment Frequency");

        DecrementFrequencyButton.setText("Decrement Frequency");

        VolumeDisplay.setText("5");

        javax.swing.GroupLayout RadioPanelLayout = new javax.swing.GroupLayout(RadioPanel);
        RadioPanel.setLayout(RadioPanelLayout);
        RadioPanelLayout.setHorizontalGroup(
            RadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RadioPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FMButton)
                .addGap(86, 86, 86)
                .addComponent(AMButton)
                .addGap(178, 178, 178))
            .addGroup(RadioPanelLayout.createSequentialGroup()
                .addGroup(RadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(RadioPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IncrementFrequencyButton)
                        .addGap(18, 18, 18)
                        .addComponent(DecrementFrequencyButton))
                    .addGroup(RadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(RadioPanelLayout.createSequentialGroup()
                            .addGap(126, 126, 126)
                            .addComponent(FrequencyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(RadioPanelLayout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(IncrementVolumeButton)
                            .addGap(18, 18, 18)
                            .addComponent(DecrementVolumeButton)
                            .addGap(34, 34, 34)
                            .addComponent(VolumeLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(VolumeDisplay))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        RadioPanelLayout.setVerticalGroup(
            RadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RadioPanelLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(RadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IncrementFrequencyButton)
                    .addComponent(DecrementFrequencyButton))
                .addGap(43, 43, 43)
                .addGroup(RadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DecrementVolumeButton)
                    .addComponent(IncrementVolumeButton)
                    .addComponent(VolumeLabel)
                    .addComponent(VolumeDisplay))
                .addGap(48, 48, 48)
                .addComponent(FrequencyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AMButton)
                    .addComponent(FMButton))
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Radio", RadioPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Clock");

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SnoozeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnoozeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SnoozeButtonActionPerformed

    private void HourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HourButtonActionPerformed
        // TODO add your handling code here:
        this.controller.userIncrementHour();
        this.updateTimeLabel();
    }//GEN-LAST:event_HourButtonActionPerformed

    private void Alarm1ToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alarm1ToggleButtonActionPerformed
        // TODO add your handling code here:
        this.controller.toggleSetAlarm1();
        this.updateTimeLabel();
    }//GEN-LAST:event_Alarm1ToggleButtonActionPerformed

    private void TimeToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeToggleButtonActionPerformed
        // TODO add your handling code here:
        this.controller.toggleSetTime();
    }//GEN-LAST:event_TimeToggleButtonActionPerformed

    private void MinuteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinuteButtonActionPerformed
        // TODO add your handling code here:
        this.controller.userIncrementMinute();
        this.updateTimeLabel();
    }//GEN-LAST:event_MinuteButtonActionPerformed

    private void Alarm2ToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alarm2ToggleButtonActionPerformed
        // TODO add your handling code here:
        this.controller.toggleSetAlarm2();
        this.updateTimeLabel();
    }//GEN-LAST:event_Alarm2ToggleButtonActionPerformed

    private void Alarm1OnOffSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alarm1OnOffSwitchActionPerformed
        // TODO add your handling code here:
        if(this.Alarm1OnOffSwitch.isSelected())
        {
            this.Alarm1OnOffSwitch.setText("Alarm 1 On");
            this.controller.toggleAlarm1EnabledBoolean();
        }
        else
        {
            this.Alarm1OnOffSwitch.setText("Alarm 1 Off");
            this.controller.toggleAlarm1EnabledBoolean();

        }
    }//GEN-LAST:event_Alarm1OnOffSwitchActionPerformed

    private void Alarm2OnOffSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alarm2OnOffSwitchActionPerformed
        // TODO add your handling code here:
        if(this.Alarm2OnOffSwitch.isSelected())
        {
            this.Alarm2OnOffSwitch.setText("Alarm 2 On");
            this.controller.toggleAlarm2EnabledBoolean();

        }
        else
        {
            this.Alarm2OnOffSwitch.setText("Alarm 2 Off");
            this.controller.toggleAlarm2EnabledBoolean();

        }
    }//GEN-LAST:event_Alarm2OnOffSwitchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OreoAlarmClockJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OreoAlarmClockJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OreoAlarmClockJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OreoAlarmClockJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OreoAlarmClockJFrame().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AMButton;
    private javax.swing.JToggleButton Alarm1OnOffSwitch;
    private javax.swing.JToggleButton Alarm1ToggleButton;
    private javax.swing.JToggleButton Alarm2OnOffSwitch;
    private javax.swing.JToggleButton Alarm2ToggleButton;
    private javax.swing.JPanel ClockPanel;
    private javax.swing.JButton DecrementFrequencyButton;
    private javax.swing.JButton DecrementVolumeButton;
    private javax.swing.ButtonGroup FMAMButtonGroup;
    private javax.swing.JRadioButton FMButton;
    private javax.swing.JLabel FrequencyLabel;
    private javax.swing.JButton HourButton;
    private javax.swing.JButton IncrementFrequencyButton;
    private javax.swing.JButton IncrementVolumeButton;
    private javax.swing.JButton MinuteButton;
    private javax.swing.JPanel RadioPanel;
    private javax.swing.JButton SnoozeButton;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JToggleButton TimeToggleButton;
    private javax.swing.JLabel VolumeDisplay;
    private javax.swing.JLabel VolumeLabel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    Controller controller;
    
    private void blinkTime()
    {
        this.TimeLabel.setVisible(!this.TimeLabel.isVisible());
    }
    
    private void blinkBackground()
    {
        if(this.controller.isAlarmSounding() && this.Alarm1OnOffSwitch.isSelected())
        {
            this.jPanel3.setBackground(Color.magenta);
            this.jPanel3.setVisible(!this.jPanel3.isVisible());
        }
    }
    
    private void updateTimeLabel() {
        
        if(this.TimeToggleButton.isSelected()) {
            blinkTime();
            this.TimeLabel.setText(this.controller.getTime().toString());
        } else if(this.Alarm1ToggleButton.isSelected()) {
            blinkTime();
            this.TimeLabel.setText(this.controller.getAlarm1Time());
        } else if(this.Alarm2ToggleButton.isSelected()) {
            blinkTime();
            this.TimeLabel.setText(this.controller.getAlarm2Time());    
        } else {
            this.TimeLabel.setVisible(true);
            this.TimeLabel.setText(this.controller.getTime().toString());
            blinkBackground();
        }
        
    }


}
